### ISSUE TITLE
Getting SECURITY_ERR after selecting image

### ISSUE THREAD

**Issue by elsopi** [aaronksaunders/ionic4-firebase-storage#10]
Hello, the script doesn't seem to work when i tried it. Please see the attached image below.
![Screen Shot 2019-12-04 at 11 10 38 AM](https://user-images.githubusercontent.com/4680734/70133862-398a9180-1687-11ea-8c90-74fda17beecd.png)

I think this might have to do with File plugin, because in the console, the error appears after fileName. Any idea on how to fix this?
Thanks in advance

**Comment by elsopi** [comment]
I think this might have to do with File plugin, because in the console, the error appears after fileName. Any idea on how to fix this? 
Thanks in advance

**Comment by aaronksaunders** [comment]
will take a look

**Comment by aaronksaunders** [comment]
please check the new branch

**Comment by elsopi** [comment]
It works fine now. Thank you
